### ISSUE TITLE
An exception thrown during use causes the application to crash

### ISSUE THREAD

**Issue by Nevall** [jitendra3109/SquareGameApp#1]
An exception thrown during use causes the application to crash：
Log:
04-24 04:18:23.015 3711-3711/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.example.pcsaini779.hackathon, PID: 3711
                                                 java.lang.IllegalArgumentException: n <= 0: 0
                                                     at java.util.Random.nextInt(Random.java:182)
                                                     at com.example.pcsaini779.hackathon.Game$3.onClick(Game.java:122)
                                                     at android.view.View.performClick(View.java:4780)
                                                     at android.view.View$PerformClick.run(View.java:19866)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
04-24 04:18:23.032 2036-2071/system_process E/InputDispatcher: channel '2bcdd2f5 com.example.pcsaini779.hackathon/com.example.pcsaini779.hackathon.Game (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by jitendra3109** [comment]
@Nevall Thank you for reporting the issue I will see you  in the later what is the problem because my end term is ongoing sorry for that.
IF you fixed then it will  be honored.
